# Generated by Django 4.0.5 on 2022-09-07 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alumno_clase_codigoqr_seccion_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='claseProfe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.profesor'),
            preserve_default=False,
        ),
    ]
