# Generated by Django 4.0.5 on 2022-09-07 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clase_claseprofe'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='claseSeccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.seccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigoqr',
            name='codigoClase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.clase'),
            preserve_default=False,
        ),
    ]
