# Generated by Django 4.0.5 on 2022-10-26 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clase_claseseccion_codigoqr_codigoclase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='profeDv',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='profeRut',
        ),
    ]
