# Generated by Django 4.0.5 on 2022-10-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_profesor_profedv_remove_profesor_proferut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='profeNombre',
        ),
        migrations.AddField(
            model_name='profesor',
            name='profeMail',
            field=models.CharField(default='asd@asd.cl', max_length=100),
            preserve_default=False,
        ),
    ]
